### ISSUE TITLE
manual immutability

### ISSUE THREAD

**Issue by SteveALee** [Paqmind/styleguides#1]
For option 6 you can use ESLint's  immutable plug in. It's not perfect but I'm trying it with reasonable results. You get feedback in editors that lint eg vs code. 

. Also you can use deepfreeze in your unit tests

Great resource, thanks

**Comment by ivan-kleshnin** [comment]
> For option 6 you can use ESLint's immutable plug in. It's not perfect but I'm trying it with reasonable results. You get feedback in editors that lint eg vs code.

Good idea, thank you for information. 
Sometimes you need a minimal bundle so none library is appropriate.

> Also you can use deepfreeze in your unit tests

Could you elaborate?

**Comment by SteveALee** [comment]
> > Also you can use deepfreeze in your unit tests
> 
> Could you elaborate?

Run [deep-freeze](https://github.com/substack/deep-freeze) on your objects as part of your unit tests. This is installs tests for mutation and asserts as your test run. That way you don't have the overhead at run time but a test time. Obviously you need good coverage.

I got the idea from [Don Abramov](https://egghead.io/lessons/javascript-redux-avoiding-array-mutations-with-concat-slice-and-spread)

**Comment by ivan-kleshnin** [comment]
Got it – thanks! I updated the guide 😉
